CREATE TABLE `User` (
`userID` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `Board`(
`boardID` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, 
`title` VARCHAR (255) NOT NULL,
`position` SMALLINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `Thread`(
`threadID` INT UNISNIGED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`title` VARCHAR (255) NOT NULL,
`date` DATETIME NOT NULL,
`postCount` INT NOT NULL DEFAULT 0,
`visitCount` INT NOT NULL DEFAULT 0,
`userID` INT UNSIGNED NOT NULL,
CONSTRAINT `fkBoardUser` FOREIGN KEY (`userID`) REFERENCES `User`(`userID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `Post`(
`postID` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`title` VARCHAR (255) NOT NULL,
`created` DATETIME NOT NULL,
`modified` DATETIME NOT NULL,
`userID` INT UNSIGNED NOT NULL,
`modifiedBy` INT UNSIGNED NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
